CREATE TABLE IF NOT EXISTS organizations (
  organization_id TEXT PRIMARY KEY,
  partida TEXT,
  nombre_partida TEXT,
  capitulo TEXT,
  nombre_capitulo TEXT,
  area TEXT,
  nombre_area TEXT,
  first_seen DATE,
  last_seen DATE,
  data_coverage_type TEXT,
  source_system TEXT NOT NULL DEFAULT 'PRESUPUESTO_ABIERTO'
);

CREATE TABLE IF NOT EXISTS recipients (
  recipient_id TEXT PRIMARY KEY,
  source_identity_key TEXT,
  identity_key_type TEXT NOT NULL,
  rut TEXT,
  nombre TEXT,
  nombre_normalizado TEXT,
  is_provider BOOLEAN NOT NULL DEFAULT FALSE,
  is_person BOOLEAN NOT NULL DEFAULT FALSE,
  is_honorarium BOOLEAN NOT NULL DEFAULT FALSE,
  first_seen DATE,
  last_seen DATE,
  source_system TEXT NOT NULL DEFAULT 'PRESUPUESTO_ABIERTO'
);

CREATE TABLE IF NOT EXISTS providers (
  provider_id TEXT PRIMARY KEY,
  recipient_id TEXT NOT NULL REFERENCES recipients(recipient_id),
  rut TEXT,
  nombre TEXT,
  source_identity_key TEXT,
  identity_key_type TEXT,
  first_seen DATE,
  last_seen DATE,
  source_system TEXT NOT NULL DEFAULT 'PRESUPUESTO_ABIERTO'
);

CREATE TABLE IF NOT EXISTS transactions (
  transaction_id TEXT PRIMARY KEY,
  periodo INTEGER,
  mes INTEGER,
  organization_id TEXT REFERENCES organizations(organization_id),
  recipient_id TEXT NOT NULL REFERENCES recipients(recipient_id),
  provider_id TEXT REFERENCES providers(provider_id),
  beneficiary_source_id TEXT,
  beneficiary_id_type TEXT,
  rut_beneficiario TEXT,
  nombre_beneficiario TEXT,
  subtitulo TEXT,
  nombre_subtitulo TEXT,
  item TEXT,
  nombre_item TEXT,
  asignacion TEXT,
  nombre_asignacion TEXT,
  numero_documento TEXT,
  fecha_documento DATE,
  tipo_documento TEXT,
  orden_compra TEXT,
  fecha_ingreso DATE,
  fecha_recepcion_conforme DATE,
  moneda_presupuestaria TEXT,
  monto_devengado NUMERIC,
  monto_devengado_original NUMERIC,
  fecha_pago DATE,
  monto_pago NUMERIC,
  monto_pago_original NUMERIC,
  folio TEXT,
  codigo_bip TEXT,
  nombre_bip TEXT,
  codigo_ubicacion_geografica TEXT,
  nombre_ubicacion_geografica TEXT,
  codigo_programa_presupuestario TEXT,
  nombre_programa_presupuestario TEXT,
  sector TEXT,
  region TEXT,
  dias_de_pago TEXT,
  is_provider BOOLEAN,
  is_person BOOLEAN,
  is_honorarium BOOLEAN,
  is_intra_state BOOLEAN,
  is_floating_debt BOOLEAN,
  is_aggregated BOOLEAN,
  record_class TEXT NOT NULL DEFAULT 'SOURCE_FACT',
  source_url TEXT,
  source_file TEXT
);
